import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { ProfitInputs, ProfitOutputs } from "@/types";

export function exportProfitReport(
  inputs: ProfitInputs,
  outputs: ProfitOutputs,
  scenarioName = "ProfitOS Report"
) {
  const doc = new jsPDF();
  const date = new Date().toLocaleDateString("en-IN");

  doc.setFontSize(20);
  doc.setTextColor(99, 102, 241);
  doc.text("ProfitOS", 14, 20);
  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text(`${scenarioName} — ${date}`, 14, 28);

  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text("Profit Summary", 14, 42);

  autoTable(doc, {
    startY: 48,
    head: [["Metric", "Value"]],
    body: [
      ["Net Profit / Order", `₹${outputs.netProfit.toFixed(2)}`],
      ["Net Margin", `${outputs.netMarginPercent.toFixed(2)}%`],
      ["Gross Profit / Order", `₹${outputs.grossProfit.toFixed(2)}`],
      ["Break-even ROAS", `${outputs.breakEvenRoas.toFixed(2)}x`],
      ["Monthly Projected Profit", `₹${outputs.monthlyProjectedProfit.toLocaleString("en-IN")}`],
    ],
    theme: "striped",
    headStyles: { fillColor: [99, 102, 241] },
  });

  const finalY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable
    ?.finalY ?? 100;

  doc.setFontSize(14);
  doc.text("Inputs", 14, finalY + 15);

  autoTable(doc, {
    startY: finalY + 20,
    head: [["Input", "Value"]],
    body: [
      ["Selling Price", `₹${inputs.sellingPrice}`],
      ["Product Cost", `₹${inputs.productCost}`],
      ["RTO Rate", `${inputs.rtoRate}%`],
      ["Return Rate", `${inputs.returnRate}%`],
      ["Monthly Orders", `${inputs.monthlyOrders}`],
      ["Ad Spend", `₹${inputs.adSpend.toLocaleString("en-IN")}`],
    ],
    theme: "striped",
    headStyles: { fillColor: [99, 102, 241] },
  });

  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text("Generated by ProfitOS — profitos.app", 14, 285);

  doc.save(`profitos-report-${Date.now()}.pdf`);
}
